BEGIN;

WITH upsert_projects AS (
  INSERT INTO projects (
    title,
    slug,
    category,
    year,
    status,
    short_description,
    description,
    cover_image,
    external_url,
    video_embed,
    seo_title,
    seo_description,
    sort_order,
    published_at
  ) VALUES
  (
    'Dede & Caca',
    'dede-caca',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/1.dedeCaca.png',
    NULL,
    'https://youtube.com/embed/cR_F-brz09I?si=M8c6iNUEviekBELv',
    'Dede & Caca | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    101,
    NOW()
  ),
  (
    'Tasya & Amin',
    'tasya-amin',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/2.tasyaAmin.png',
    NULL,
    'https://youtube.com/embed/cW3G1YvVhKo?si=PGAi972cWErz6tNW',
    'Tasya & Amin | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    102,
    NOW()
  ),
  (
    'Indah & Danny',
    'indah-danny',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/3.indahDanny.png',
    NULL,
    'https://youtube.com/embed/Y2j2R59rNc8?si=sMogp0aDJBVIaV2h',
    'Indah & Danny | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    103,
    NOW()
  ),
  (
    'Hilda & Indra',
    'hilda-indra',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/4.hildaIndra.png',
    NULL,
    'https://youtube.com/embed/Jrb0DQYFvh0?si=TXXpbR135yC-Ew7C',
    'Hilda & Indra | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    104,
    NOW()
  ),
  (
    'Selvie & Dahlan',
    'selvie-dahlan',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/5.selvieDahlan.png',
    NULL,
    'https://youtube.com/embed/TrrvJQyWQ8Q?si=j2fHVktnrxwdXvq2',
    'Selvie & Dahlan | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    105,
    NOW()
  ),
  (
    'Dela & Ilham',
    'dela-ilham',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/6.delaIlham.png',
    NULL,
    'https://youtube.com/embed/JHJ0C25BTcs?si=e1YwsFUHI2B-qGEA',
    'Dela & Ilham | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    106,
    NOW()
  ),
  (
    'Fachmy & Widya',
    'fachmy-widya',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/7.fachmyWidya.png',
    NULL,
    'https://youtube.com/embed/d5nc_N3RFmQ?si=2ISd416Oi2w9Kjlw',
    'Fachmy & Widya | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    107,
    NOW()
  ),
  (
    'Icha & Haris',
    'icha-haris',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/8.ichaHaris.png',
    NULL,
    'https://youtube.com/embed/4FSMtcSgl2M?si=rvxnlqEefH13g-QU',
    'Icha & Haris | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    108,
    NOW()
  ),
  (
    'Adit & Eliza',
    'adit-eliza',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/9.aditEliza.png',
    NULL,
    'https://youtube.com/embed/0aHDCRZd6p8?si=K72FTyEP2DeAAF4q',
    'Adit & Eliza | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    109,
    NOW()
  ),
  (
    'Citra & Roby',
    'citra-roby',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/10.citraRoby.png',
    NULL,
    'https://youtube.com/embed/9clzKIIv8C4?si=oc0QDUOM7f9ZNntK',
    'Citra & Roby | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    110,
    NOW()
  ),
  (
    'Fitri & Hazami',
    'fitri-hazami',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/11.fitriHazami.png',
    NULL,
    'https://youtube.com/embed/JDxmYKRLCb0?si=d3tTWWzuESaFGB33',
    'Fitri & Hazami | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    111,
    NOW()
  ),
  (
    'Hablina & Annand',
    'hablina-annand',
    'video',
    '2026',
    'published',
    'A cinematic wedding film focused on emotion, rhythm, and real moments.',
    'A wedding motion work created to capture intimate moments, atmosphere, and emotional storytelling through cinematic pacing.',
    '/portfolio/videos/thumbnailWedding/12.hablinaAnnand.png',
    NULL,
    'https://youtube.com/embed/cBOktlmkHfE?si=bMcop5V29FXNQJ6b',
    'Hablina & Annand | Wedding Video',
    'Wedding cinematic video project by Irawan Ardiantoro.',
    112,
    NOW()
  ),
  (
    'Handy & Vidia',
    'handy-vidia',
    'video',
    '2026',
    'published',
    'A prewedding motion work with romantic visuals and cinematic pacing.',
    'A prewedding video project focused on mood, atmosphere, and visual storytelling before the wedding day.',
    '/portfolio/videos/thumbnailPrewedding/1.handyVidia.png',
    NULL,
    'https://youtube.com/embed/TkADNZS0WPw?si=zlCVyYnmhhYHsmVH',
    'Handy & Vidia | Prewedding Video',
    'Prewedding video project by Irawan Ardiantoro.',
    201,
    NOW()
  ),
  (
    'Lia & Hilman',
    'lia-hilman',
    'video',
    '2026',
    'published',
    'A prewedding motion work with romantic visuals and cinematic pacing.',
    'A prewedding video project focused on mood, atmosphere, and visual storytelling before the wedding day.',
    '/portfolio/videos/thumbnailPrewedding/2.liaHilman.png',
    NULL,
    'https://youtube.com/embed/3112_LWFt3U?si=1pgpoefvY776ODMB',
    'Lia & Hilman | Prewedding Video',
    'Prewedding video project by Irawan Ardiantoro.',
    202,
    NOW()
  ),
  (
    'Iklan Penjualan Rumah | 1',
    'iklan-penjualan-rumah-1',
    'video',
    '2026',
    'published',
    'A product advertisement video created for property marketing.',
    'A commercial motion work designed to present property selling points through simple, clear, and visual storytelling.',
    '/portfolio/videos/thumbnailProductAdvertisement/1.png',
    NULL,
    'https://youtube.com/embed/EyfJXzMpeeE?si=QhLxXrhtfEfEPzuI',
    'Iklan Penjualan Rumah 1 | Product Advertisement',
    'Product advertisement video project by Irawan Ardiantoro.',
    301,
    NOW()
  ),
  (
    'Iklan Penjualan Rumah | 2',
    'iklan-penjualan-rumah-2',
    'video',
    '2026',
    'published',
    'A product advertisement video created for property marketing.',
    'A commercial motion work designed to present property selling points through simple, clear, and visual storytelling.',
    '/portfolio/videos/thumbnailProductAdvertisement/2.png',
    NULL,
    'https://youtube.com/embed/2glEiz8H9lk?si=WsEcn3pPbfL-sghC',
    'Iklan Penjualan Rumah 2 | Product Advertisement',
    'Product advertisement video project by Irawan Ardiantoro.',
    302,
    NOW()
  ),
  (
    'Iklan Penjualan Rumah | 3',
    'iklan-penjualan-rumah-3',
    'video',
    '2026',
    'published',
    'A product advertisement video created for property marketing.',
    'A commercial motion work designed to present property selling points through simple, clear, and visual storytelling.',
    '/portfolio/videos/thumbnailProductAdvertisement/3.png',
    NULL,
    'https://youtube.com/embed/UdyBbU43tpo?si=4SkUbr_r6-Z0qQ83',
    'Iklan Penjualan Rumah 3 | Product Advertisement',
    'Product advertisement video project by Irawan Ardiantoro.',
    303,
    NOW()
  ),
  (
    'Iklan Penjualan Kopi | 1',
    'iklan-penjualan-kopi-1',
    'video',
    '2026',
    'published',
    'A product advertisement video created for coffee product promotion.',
    'A commercial motion work designed to highlight coffee products through visual mood, rhythm, and simple storytelling.',
    '/portfolio/videos/thumbnailProductAdvertisement/4.jpg',
    NULL,
    'https://youtube.com/embed/5mswaGgylak',
    'Iklan Penjualan Kopi 1 | Product Advertisement',
    'Product advertisement video project by Irawan Ardiantoro.',
    304,
    NOW()
  ),
  (
    'Iklan Penjualan Kopi | 2',
    'iklan-penjualan-kopi-2',
    'video',
    '2026',
    'published',
    'A product advertisement video created for coffee product promotion.',
    'A commercial motion work designed to highlight coffee products through visual mood, rhythm, and simple storytelling.',
    '/portfolio/videos/thumbnailProductAdvertisement/5.jpg',
    NULL,
    'https://youtube.com/embed/RlIGZMERe8g',
    'Iklan Penjualan Kopi 2 | Product Advertisement',
    'Product advertisement video project by Irawan Ardiantoro.',
    305,
    NOW()
  )
  ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    year = EXCLUDED.year,
    status = EXCLUDED.status,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    cover_image = EXCLUDED.cover_image,
    external_url = EXCLUDED.external_url,
    video_embed = EXCLUDED.video_embed,
    seo_title = EXCLUDED.seo_title,
    seo_description = EXCLUDED.seo_description,
    sort_order = EXCLUDED.sort_order,
    published_at = COALESCE(projects.published_at, NOW()),
    updated_at = NOW()
  RETURNING id, slug
)
DELETE FROM project_tags
WHERE project_id IN (SELECT id FROM projects WHERE category = 'video');

INSERT INTO project_tags (project_id, tag, sort_order)
SELECT id, 'Wedding', 1 FROM projects WHERE slug IN (
  'dede-caca',
  'tasya-amin',
  'indah-danny',
  'hilda-indra',
  'selvie-dahlan',
  'dela-ilham',
  'fachmy-widya',
  'icha-haris',
  'adit-eliza',
  'citra-roby',
  'fitri-hazami',
  'hablina-annand'
);

INSERT INTO project_tags (project_id, tag, sort_order)
SELECT id, 'Prewedding', 1 FROM projects WHERE slug IN (
  'handy-vidia',
  'lia-hilman'
);

INSERT INTO project_tags (project_id, tag, sort_order)
SELECT id, 'Product Advertisement', 1 FROM projects WHERE slug IN (
  'iklan-penjualan-rumah-1',
  'iklan-penjualan-rumah-2',
  'iklan-penjualan-rumah-3',
  'iklan-penjualan-kopi-1',
  'iklan-penjualan-kopi-2'
);

INSERT INTO project_tags (project_id, tag, sort_order)
SELECT id, 'Cinematic', 2 FROM projects WHERE category = 'video';

INSERT INTO project_tags (project_id, tag, sort_order)
SELECT id, 'Motion Work', 3 FROM projects WHERE category = 'video';

COMMIT;